-- NOTE: semi-colons on new-line
CREATE UNIQUE INDEX IDX_UK_ACT_CODE_PRJ_CODE ON CMN_ACTIVITIES 
( 
        CASE WHEN ROW_STATUS = 0 THEN PROJECT_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN ACTIVITY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_ADDRESS_BOOKS_CODE ON CMN_ADDRESS_BOOKS 
( 
        CASE WHEN ROW_STATUS = 0 THEN ADDRESS_BOOKS_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_AP_INVOICES ON CMN_AP_INVOICES 
( 
        CASE WHEN ROW_STATUS = 0 THEN DOCUMENT_NUMBER ELSE NULL END,
        CASE WHEN ROW_STATUS = 0 THEN DOC_TYPE ELSE NULL END,
        CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END,
        CASE WHEN ROW_STATUS = 0 THEN PAY_ITEM ELSE NULL END
        
)
;
CREATE UNIQUE INDEX IDX_UK_CODE_TABLE ON CMN_CODE_TABLE 
( 
        CASE WHEN ROW_STATUS = 0 THEN CODE_TYPE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN CODE_NAME ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_COMPANIES ON CMN_COMPANIES 
( 
        CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_COST_CENTRES ON CMN_COST_CENTRES 
( 
        CASE WHEN ROW_STATUS = 0 THEN COST_CENTRE_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_CURRENCY_CODE ON CMN_CURRENCIES 
( 
        CASE WHEN ROW_STATUS = 0 THEN CURRENCY_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_CUSTOMER_CODE ON CMN_CUSTOMERS 
( 
        CASE WHEN ROW_STATUS = 0 THEN CUSTOMER_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_DEPARTMENT_CODE ON CMN_DEPARTMENTS 
( 
        CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN BU_CODE ELSE NULL END
)
;  
CREATE UNIQUE INDEX IDX_UK_EMP_NO ON CMN_EMP ( CASE WHEN ROW_STATUS = 0 AND EMPLOYEE_NO IS NOT NULL THEN EMPLOYEE_NO ELSE NULL END )
;
CREATE UNIQUE INDEX IDX_UK_EMP_POSITION_CODE ON CMN_EMP_POSITIONS 
( 
        CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
/*
  Any datetime data must include the Time values even if sending source only has date.
  e.g. EFFECTIVE_FROM 2014-12-25 must contain time as in 2014-12-25T00:00:00
  PS JOB_DATA
  Example - update same record
  EMP_NO EFFECTIVE_FROM      OCCUPATION  JOBROLE     PS_RECORD_NO SEQ_NO
  E001   2010-01-01T00:00:00 BULLSHIT    SALES MGR   0            0
  E001   2010-01-01T00:00:00 BULLSHITER  SALES MGR   0            1
  ...
  Example - employee promoted on 2013, followed by update
  EMP_NO EFFECTIVE_FROM      OCCUPATION      JOBROLE         PS_RECORD_NO SEQ_NO
  E001   2010-01-01T00:00:00 BULLSHIT        SALES MGR       0            0
  E001   2010-01-01T00:00:00 BULLSHITER      SALES MGR       0            1
  E001   2013-01-01T00:00:00 BULLSHITER      SNR SALES MGR   0            0
  E001   2013-01-01T00:00:00 BULLSHITER PRO  SNR SALES MGR   0            1
  ...
  Example - employee assign dual role with same effective date but new PS_RECORD_NO, JOB_INDICATOR indicates P as Primary role.
  EMP_NO EFFECTIVE_FROM      OCCUPATION      JOBROLE         PS_RECORD_NO SEQ_NO JOB_INDICATOR
  E002   2015-01-01T00:00:00 BULLSHITER PRO  SNR SALES MGR   0            0      P
  E002   2015-01-01T00:00:00 BULLSHITER PRO  ASST V.P.       1            0
*/
CREATE UNIQUE INDEX IDX_UK_EMPLOYMENTS ON CMN_EMPLOYMENTS 
( 
        CASE WHEN ROW_STATUS = 0 THEN EMPLOYEE_NO ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN EFFECTIVE_FROM ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN PS_RECORD_NO ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN SEQ_NO ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_EQUIPMENT_CODE ON CMN_EQUIPMENTS 
( 
        CASE WHEN ROW_STATUS = 0 THEN EQUIPMENT_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_LEAVES ON CMN_LEAVES 
( 
        CASE WHEN ROW_STATUS = 0 THEN EMPLOYEE_NO ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN PS_RECORD_NO ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_PROJECT_CODE ON CMN_PROJECTS 
( 
        CASE WHEN ROW_STATUS = 0 THEN PROJECT_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_SUPPLIER_CODE ON CMN_SUPPLIERS 
( 
        CASE WHEN ROW_STATUS = 0 THEN SUPPLIER_CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_TAX_CODE ON CMN_TAXES 
( 
        CASE WHEN ROW_STATUS = 0 THEN TAX_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_WORK_ORDER ON CMN_WORK_ORDERS 
( 
        CASE WHEN ROW_STATUS = 0 THEN WORK_ORDER_NO ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN COMPANY_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_PUBLIC_HOLIDAYS ON CMN_PUBLIC_HOLIDAYS 
( 
        CASE WHEN ROW_STATUS = 0 THEN HOLIDAY_DATE ELSE NULL END
		, CASE WHEN ROW_STATUS = 0 THEN PS_HOLIDAY_SCHEDULE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_NAT_CODE ON CMN_NATIONALITIES 
( 
        CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
        ,CASE WHEN ROW_STATUS = 0 THEN ID_TYPE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_JOB_ROLES ON CMN_JOB_ROLES 
( 
        CASE WHEN ROW_STATUS = 0 THEN BU_CODE ELSE NULL END     
        ,CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
    ,CASE WHEN ROW_STATUS = 0 THEN EFFECTIVE_FROM ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_BU_HRS ON CMN_BUSINESS_UNITS_HR 
( 
        CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_LOCS ON CMN_LOCATIONS 
( 
        CASE WHEN ROW_STATUS = 0 THEN BU_CODE ELSE NULL END     
        ,CASE WHEN ROW_STATUS = 0 THEN CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_ITEM_CODE ON CMN_ITEMS 
( 
    CASE WHEN ROW_STATUS = 0 THEN ITEM_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_BU_HR_TYP_CODE ON CMN_M_BUSINESS_UNIT_TYPES 
( 
    CASE WHEN ROW_STATUS = 0 THEN BUSINESS_UNIT_TYPE_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_EMP_GRADE_CODE ON CMN_EMP_GRADES 
( 
    CASE WHEN ROW_STATUS = 0 THEN GRADE_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_SAL_ADMIN_PLAN_CODE ON CMN_SAL_ADMIN_PLANS 
( 
    CASE WHEN ROW_STATUS = 0 THEN PLAN_CODE ELSE NULL END
)
;
CREATE UNIQUE INDEX IDX_UK_JOB_CODE ON CMN_JOB_CODES 
( 
    CASE WHEN ROW_STATUS = 0 THEN JOB_CODE ELSE NULL END
)
;
