-- NOTE: semi-colons on new-line
COMMENT ON TABLE CMN.CMN_EMP IS 'main employee records'
;
COMMENT ON TABLE CMN.CMN_CODE_TABLE IS 'Code table for generic code and name e.g. Country, Nationality, Race, Religion etc.'
;
COMMENT ON COLUMN CMN.CMN_ACTIVITIES.ACTIVITY_CODE IS 'F0901.SUB'
;
COMMENT ON COLUMN CMN.CMN_ACTIVITIES.ACTIVITY_NAME IS 'F0901.DL01'
;
COMMENT ON COLUMN CMN.CMN_ACTIVITIES.PROJECT_CODE IS 'F0901.MCU '
;
COMMENT ON COLUMN CMN.CMN_ACTIVITIES.COMPANY_CODE IS 'F0901.CO '
;
COMMENT ON COLUMN CMN.CMN_ACTIVITIES.ACTIVITY_TYPE IS 'F0901.OBJ'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.ADDRESS_BOOKS_CODE IS 'F0101.AN8'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.ADDRESS_BOOKS_NAME IS 'F0101.ALPH'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.ADDRESS_BOOKS_ADDRESS IS 'F0101.ADD1, ADD2, ADD3, ADD4, CTY1, ADDS, ADDZ, CTR'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.ADDRESS_BOOKS_CATEGORY IS 'F0101.AT1'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.MODIFIED_ON IS 'JDE MODIFIED DATE'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.MODIFIED_BY IS 'JDE MODIFIED PERSON'
;
COMMENT ON COLUMN CMN.CMN_ADDRESS_BOOKS.SYNC_ON IS 'DATA TRASNFER DATE FROM JDE'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.INVOICE_NO IS 'F0411.VINV'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.INVOICE_DATE IS 'F0411.DIVJ'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.DOCUMENT_NUMBER IS 'F0411.DOC'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.PO IS 'F0411.PO'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.ADDRESS_BOOK_CODE IS 'F0411.AN8'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.DUE_DATE IS 'F0411.DDJ'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.CURRENCY_CODE IS 'F0411.CRCD'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.GROSS_AMOUNT IS 'F0411.AG'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.GST_TYPE IS 'F0411.EXR1'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.DISCOUNT IS 'F0411.ADSC'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.INVOICE_STATUS IS 'F0411.PST'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.COMPANY_CODE IS 'F0411.KCO'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.MODIFIED_BY IS 'F0411.USER'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.MODIFIED_ON IS 'F0411.UPMJ, F0411.UPMT'
;
COMMENT ON COLUMN CMN.CMN_AP_INVOICES.SYNC_ON IS 'DATA TRANSFER DATE FROM JDE'
;
COMMENT ON COLUMN CMN.CMN_COMPANIES.COMPANY_CODE IS 'F0010.CO'
;
COMMENT ON COLUMN CMN.CMN_COMPANIES.COMPANY_NAME IS 'F0010.NAME'
;
COMMENT ON COLUMN CMN.CMN_COST_CENTRES.COST_CENTRE_CODE IS 'F0006.MCU'
;
COMMENT ON COLUMN CMN.CMN_COST_CENTRES.COST_CENTRE_NAME IS 'F0006.DC'
;
COMMENT ON COLUMN CMN.CMN_COST_CENTRES.COMPANY_CODE IS 'F0006.CO'
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.EQUIPMENT_CODE IS 'F1201.APID'
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.EQUIPMENT_NAME IS 'F1201.DL03'
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.EQUIPMENT_ASSET_NO IS 'F1201.NUMB'
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.CATEGORY IS 'ACL1 '
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.EQUIPMENT_STATUS IS 'F1201.EQST '
;
COMMENT ON COLUMN CMN.CMN_EQUIPMENTS.COST_CENTRE_CODE IS 'MCU'
;
COMMENT ON COLUMN CMN.CMN_PROJECTS.PROJECT_CODE IS 'MCU (F0006)'
;
COMMENT ON COLUMN CMN.CMN_PROJECTS.PROJECT_NAME IS 'DL01 (F0006)'
;
COMMENT ON COLUMN CMN.CMN_PROJECTS.PROJECT_START_DATE IS 'F0006.D2J'
;
COMMENT ON COLUMN CMN.CMN_PROJECTS.PROJECT_END_DATE IS ' F0006.D4J'
;
COMMENT ON COLUMN CMN.CMN_PROJECTS.COMPANY_CODE IS 'F0006.CO'
;
COMMENT ON COLUMN CMN.CMN_SUPPLIERS.SUPPLIER_CODE IS 'F0101.AN8'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.WORK_ORDER_NO IS 'F4301.DOCO'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.SUPPLIER_CODE IS 'F4301.AN8'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.COMPANY_CODE IS 'F4301.KCOO'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.ORDER_TYPE IS 'F4301.DCTO'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.BUYER_CODE IS 'F4301.ANBY'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.WORK_ORDER_DATE IS 'F4301.TRDJ'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.REQUESTED_DATE IS 'F4301.DRQJ'
;
COMMENT ON COLUMN CMN.CMN_WORK_ORDERS.CANCELLED_DATE IS 'F4301.CNDJ'
;
COMMENT ON COLUMN CMN.CMN_NATIONALITIES.CODE IS 'NID_TYPE_TBL.COUNTRY'
;
COMMENT ON COLUMN CMN.CMN_NATIONALITIES.ID_TYPE IS 'NID_TYPE_TBL.NATIONAL_ID_TYPE'
;
COMMENT ON COLUMN CMN.CMN_NATIONALITIES.NAME IS 'NID_TYPE_TBL.DESCR'
;
COMMENT ON COLUMN CMN.CMN_JOB_ROLES.BU_CODE IS 'JOBCODE_TBL.SETID'
;
COMMENT ON COLUMN CMN.CMN_JOB_ROLES.CODE IS 'JOBCODE_TBL.JOBCODE'
;
COMMENT ON COLUMN CMN.CMN_JOB_ROLES.EFFECTIVE_FROM IS 'JOBCODE_TBL.EFFDT'
;
COMMENT ON COLUMN CMN.CMN_JOB_ROLES.IS_ACTIVE IS 'JOBCODE_TBL.EFF_STATUS'
;
COMMENT ON COLUMN CMN.CMN_JOB_ROLES.NAME IS 'JOBCODE_TBL.DESCR'
;
COMMENT ON COLUMN CMN.CMN_BUSINESS_UNITS_HR.CODE IS 'BUS_UNIT_TBL_HR.BUSINESS_UNIT'
;
COMMENT ON COLUMN CMN.CMN_BUSINESS_UNITS_HR.NAME IS 'BUS_UNIT_TBL_HR.DESCR'
;
COMMENT ON COLUMN CMN.CMN_EMPLOYMENTS.EFFECTIVE_FROM IS 'Effective date of employment record, e.g. the record created_on date'
;
COMMENT ON COLUMN CMN.CMN_EMPLOYMENTS.EFFECTIVE_TO IS 'Termination date'
;
COMMENT ON COLUMN CMN.CMN_EMPLOYMENTS.EMPLOYEE_CATEGORY IS 'Staff/NTS/Non-NTS'
;
COMMENT ON COLUMN CMN.CMN_EMPLOYMENTS.REPORTING_TO_POSITION IS 'direct supervisor, primary query, store a position id'
;
COMMENT ON COLUMN CMN.CMN_EMPLOYMENTS.SUPERVISOR_NO IS 'direct supervisor, secondary query, store an employee_no'
;
