BEGIN
  FOR i IN (SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'CMN_%') 
  LOOP 
        EXECUTE IMMEDIATE 'CREATE SEQUENCE '|| SUBSTR(i.table_name,5) || '_SEQ ';
  END LOOP;
  COMMIT;
END;